[project]
name = "vmax"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115,<1.0",
]

[project.optional-dependencies]
dev = [
    "httpx2>=0.28",
]
dtb = [
    "pylibfdt>=1.7.2",
]
ssh = [
    "paramiko>=3.4,<5",
]
all = [
    "pylibfdt>=1.7.2",
    "paramiko>=3.4,<5",
]

[tool.uv]
package = false
